- hosts: localhost
  tasks:
   - include_vars: "/ansi/secret.yml"

   - command: "/ansi/photo.py"
  
   - debug:
       var: ansible_date_time     


   - mail:
      body: "Unrecognized device attached on {{ansible_date_time.date}} at {{ansible_date_time.time}}<br>You can check logs in /tmp/devices.log"
      from: '500052872@stu.upes.ac.in'
      username: '500052872@stu.upes.ac.in'
      password: "{{ password }}"
      subject: "Security alert!"
      to: 'akijain058@gmail.com'
      host: smtp.gmail.com
      port: 587
      attach: '/my.jpg'
